spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate:
      format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/postgres
  username: steve
  password: '0000'
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: project_example.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

# TODO: spring.redis.url: url 을 설정해야 redis 를 실행할 수 있음